#!/bin/bash

echo "Creating the base container… "

libertine_container_manager create -t chroot -s trusty

echo "Installing packages in the container… "
libertine_container_manager install-package -p gedit
libertine_container_manager install-package -p libreoffice
libertine_container_manager install-package -p firefox
libertine_container_manager install-package -p xchat-gnome
libertine_container_manager install-package -p gimp
