.TH libertine-launch "1" "August 2016" "libertine-launch 1.3" "User Commands"

.SH NAME
libertine-launch \- Launch an application natively or in a Libertine container

.SH DESCRIPTION
usage: libertine\-launch [\-h] [-i ID] ...
.PP
Launch an application natively or in a Libertine container

When specifying the optional -i/--id argument, it must be placed before the exec line.
.SS "positional arguments:"
.TP
app_exec_line
exec line
.SS "optional arguments:"
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-i\fR, \fB\-\-id\fR
Container identifier when launching containerized apps
