.TH libertine-session-bridge "1" "April 2016" "libertine-session-bridge 0.99" "User Commands"

.SH NAME
libertine-session-bridge \- listen for data from a DBUS session

.SH DESCRIPTION
usage: libertine\-session-bridge DBUS_SOCKET
.PP
listen for data from a DBUS session on the given socket path
.SS "positional arguments:"
.TP
DBUS_SOCKET
path to DBUS socket
