.TH libertine-launch "1" "November 2015" "libertine-launch 0.99" "User Commands"

.SH NAME
libertine-launch \- launch an application in a Libertine container

.SH DESCRIPTION
usage: libertine\-launch [\-h] container_id ...
.PP
launch an application in a Libertine container
.SS "positional arguments:"
.TP
container_id
Libertine container ID
.TP
app_exec_line
exec line
.SS "optional arguments:"
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
