
macro(list_prefix _outvar _listvar _prefix)
  set(${_outvar})
  foreach(_item IN LISTS ${_listvar})
    list(APPEND ${_outvar} ${_prefix}${_item})
  endforeach()
endmacro(list_prefix)

macro(list_make_absolute _outvar _listvar _prefix)
  set(${_outvar})
  foreach(_item IN LISTS ${_listvar})
    if(IS_ABSOLUTE ${_item})
      list(APPEND ${_outvar} ${_item})
    else()
      list(APPEND ${_outvar} ${_prefix}${_item})
    endif()
  endforeach()
endmacro(list_make_absolute)
